coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%

fixes:
  - "github.com/YElayyat/otel-cardinality-processor/::"

ignore:
  - "internal/cmd/**/*"
  - "test/**/*"
  - "examples/**/*"
  - "scripts/**/*"
  - "cardinalityprocessor/internal/metadata/**/*"
  - "cardinalityprocessor/internal/metadatatest/**/*"
  - "cardinalityprocessor/generated_*.go"
