// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("cardinality_guardian")
	ScopeName = "github.com/YElayyat/otel-cardinality-processor/cardinalityprocessor"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
